/**
 * Jalisco con empleo API
 * Aplicacion creada para conectar proovedores con clientes en Jalisco
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@amdocs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Empleo } from './empleo';

export interface Category { 
    /**
     * a
     */
    categoryId: number;
    /**
     * a
     */
    name: string;
    /**
     * a
     */
    version: string;
    /**
     * a
     */
    description: string;
    /**
     * a
     */
    imageurl: string;
    /**
     * a
     */
    empleoList: Array<Empleo>;
}