/**
 * Jalisco con empleo API
 * Aplicacion creada para conectar proovedores con clientes en Jalisco
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@amdocs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Skill { 
    /**
     * a
     */
    skillId: number;
    /**
     * a
     */
    name: string;
    /**
     * a
     */
    description: string;
    /**
     * a
     */
    version: string;
    /**
     * a
     */
    imageurl: string;
}