/**
 * Jalisco con empleo API
 * Aplicacion creada para conectar proovedores con clientes en Jalisco
 *
 * OpenAPI spec version: 1.0.0
 * Contact: soporte@amdocs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

export interface User { 
    /**
     * First Name of the User
     */
    firstName: string;
    /**
     * Last Name of the User
     */
    lastName: string;
    /**
     * Middle Name of the User
     */
    middleName?: string;
    /**
     * Requester/Provider
     */
    userType: string;
    /**
     * 10 digit Phone Number of the user
     */
    phoneNumber: string;
    /**
     * CountryCode of the user, Default Value +52
     */
    countryCode?: string;
    address?: any;
}